window.DCO_SUPABASE_CONFIG = {
  url: "sb_publishable_xEx8owWZg6mLaA85qnOnRQ_WlPBwsmQ",
  anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptdHNtb3dneWljbWpsYnJ2Y2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyMjQ1NDksImV4cCI6MjA5MzgwMDU0OX0.IDttOBElQUggAtOSnL7C2gmSVIucEQBOhqALFSZ8KUg"
};
